# Generated by Django 5.0.7 on 2024-07-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['year_level']},
        ),
    ]
